INSERT INTO EMPLOYEE_INFO (EMP_ID, EMP_NAME, EMP_ADDRESS) VALUES (1, 'Malay Chakrabarty', 'Kolkata');
INSERT INTO EMPLOYEE_INFO (EMP_ID, EMP_NAME, EMP_ADDRESS) VALUES (2, 'Tumpa Panad', 'Garia');
INSERT INTO EMPLOYEE_INFO (EMP_ID, EMP_NAME, EMP_ADDRESS) VALUES (3, 'Kaveri Thimmaiah', 'Bangalore');
INSERT INTO EMPLOYEE_INFO (EMP_ID, EMP_NAME, EMP_ADDRESS) VALUES (4, 'Sayantan Bhandra', 'Behala');